name: contentful-type-sync-test
on:
  repository_dispatch:
    types: [contentful-sync]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install axios
      - name: Remove existing cache if exists
        run: |
          if [ -f cache.json ]; then
            echo "Removing existing cache file."
            rm cache.json
          else
            echo "No cache file to remove."
          fi

      - name: Restore cache
        id: cache-contentful
        uses: actions/cache@v4
        with:
          path: cache.json
          key: Contentful-cache-${{ github.run_id }}
          restore-keys: |
            Contentful-cache-

      - name: Log cache contents if exists
        run: |
          if [ -f cache.json ]; then
            echo "Cache file exists. Contents:"
            cat cache.json
          else
            echo "Cache file does not exist."
          fi
      - name: Log GitHub token (masked)
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN_FOR_CONTENTFUL_POST_WEBHOOK }}
        run: |
          echo "GitHub token starts with: ${GITHUB_TOKEN:0:4}****"

      - name: Run server to log POST request
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN_FOR_CONTENTFUL_POST_WEBHOOK }}
        run: |
          node server.js | tee server.log &
          echo "Server is running..."
          sleep 5  # Give the server some time to start

      - name: Send repository_dispatch payload to server
        run: |
          payload=$(echo '${{ toJson(github.event.client_payload) }}' | jq -c .)
          echo "Sending payload: $payload"
          curl -X POST http://localhost:8000 -H "Content-Type: application/json" -d "$payload"

      - name: Display server logs
        run: cat server.log

      - name: Save cache
        uses: actions/cache@v4
        with:
          path: cache.json
          key: Contentful-cache-${{ github.run_id }}
