name: contentful-type-sync-test
on:
  repository_dispatch:
    types: [contentful-sync]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Restore cache
        id: cache-contentful
        uses: actions/cache@v2
        with:
          path: cache.json
          key: ${{ runner.os }}-contentful-cache
          restore-keys: |
            ${{ runner.os }}-contentful-cache

      - name: Run server to log POST request
        run: |
          node server.js | tee server.log &
          echo "Server is running..."
          sleep 5  # Give the server some time to start

      - name: Send repository_dispatch payload to server
        run: |
          payload=$(echo '${{ toJson(github.event.client_payload) }}' | jq -c .)
          echo "Sending payload: $payload"
          curl -X POST http://localhost:8000 -H "Content-Type: application/json" -d "$payload"

      - name: Display server logs
        run: cat server.log

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: cache.json
          key: ${{ runner.os }}-contentful-cache
