name: Prevent Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths-ignore:
      - "docs/**"
      - "documentation/**"
      - "**.md"
      - "**/documentation/**"
      - "CNAME*"

jobs:
  CheckDisallowedLabels:
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'labeled' || github.event.action == 'unlabeled' ||
      contains(github.event.pull_request.labels.*.name, 'Do Not Merge Yet') ||
      contains(github.event.pull_request.labels.*.name, 'in-progress')
    steps:
      - run: |
          echo "::error::PR has 'Do Not Merge Yet' or 'in-progress' label"
          echo "Please remove the label before merging"
          exit 1
